### ISSUE TITLE
Pinned tabs are broken vertical tabs

### ISSUE THREAD

**Issue by trickypr** [focus-browser/browser#212]
Pinned vertical tabs are very broken and something I want to use, need to fix it at some point

**Comment by TinkrTech** [comment]
The issue seems to be with the first unpinned tab and the pinned tabs having some conflicting positioning rule leading to overlapping. The selectors for these are `#tabbrowser-tabs[haspinnedtabs] .tabbrowser-tab[first-visible-unpinned-tab]` and `.tabbrowser-tab[pinned]` respectively.

**Comment by thepick** [comment]
Just checking in to see if there has been any progress in sorting this problem out? I just tried pinning a tab and the functionality still appears to be broken.

**Comment by trickypr** [comment]
Fixed by [`2e9d6dd`](https://github.com/pulse-browser/browser/commit/2e9d6dd09eae3749492bcde724e2c8f68be81d4a)

**Comment by thepick** [comment]
Thanks for looking into the issue, but pinned tabs still appear to be broken. Tabs opened below them glitch and flash on/off. Unpinning the tab fixes the problem. I tried opening the browser in Troubleshoot Mode and the problem persisted.
